<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="internal"
    nsURI="jpt.core.xmi" nsPrefix="jpt.core">
  <eClassifiers xsi:type="ecore:EClass" name="IJpaModel" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="JpaModel" eSuperTypes="#//JpaEObject #//IJpaModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//IJpaProject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IJpaEObject" abstract="true" interface="true">
    <eOperations name="getJpaProject" eType="#//IJpaProject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JpaEObject" abstract="true" eSuperTypes="#//IJpaEObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="IJpaProject" abstract="true" interface="true"
      eSuperTypes="#//IJpaEObject">
    <eOperations name="getModel" lowerBound="1" eType="#//IJpaModel"/>
    <eOperations name="getPlatform" ordered="false" unique="false" lowerBound="1"
        eType="#//IJpaPlatform"/>
    <eOperations name="setPlatform">
      <eParameters name="platformId" ordered="false" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="getDataSource" lowerBound="1" eType="#//IJpaDataSource"/>
    <eOperations name="setDataSource" ordered="false" unique="false" lowerBound="1">
      <eParameters name="connectionProfileName" ordered="false" unique="false" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="isDiscoverAnnotatedClasses" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eOperations name="setDiscoverAnnotatedClasses" ordered="false" unique="false"
        lowerBound="1">
      <eParameters name="discoverAnnotatedClasses" ordered="false" unique="false"
          lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JpaProject" eSuperTypes="#//JpaEObject #//IJpaProject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" ordered="false"
        unique="false" lowerBound="1" eType="#//IJpaPlatform" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" ordered="false"
        unique="false" eType="#//IJpaDataSource" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discoverAnnotatedClasses"
        ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//IJpaFile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IJpaPlatform" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IJpaDataSource" abstract="true" interface="true"
      eSuperTypes="#//IJpaEObject">
    <eOperations name="getConnectionProfileName" ordered="false" unique="false" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JpaDataSource" eSuperTypes="#//JpaEObject #//IJpaDataSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionProfileName"
        ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IJpaFile" abstract="true" interface="true"
      eSuperTypes="#//IJpaEObject">
    <eOperations name="getContentId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getContent" eType="#//IJpaRootContentNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JpaFile" eSuperTypes="#//JpaEObject #//IJpaFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//IJpaRootContentNode"
        containment="true" eOpposite="#//IJpaRootContentNode/jpaFile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IJpaSourceObject" abstract="true" interface="true"
      eSuperTypes="#//IJpaEObject">
    <eOperations name="getJpaFile" eType="#//IJpaFile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IXmlEObject" abstract="true" interface="true"
      eSuperTypes="#//IJpaEObject #//IJpaSourceObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlEObject" abstract="true" eSuperTypes="#//JpaEObject #//IXmlEObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="IJpaContentNode" abstract="true" interface="true"
      eSuperTypes="#//IJpaSourceObject">
    <eOperations name="getJpaFile" lowerBound="1" eType="#//IJpaFile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IJpaRootContentNode" abstract="true"
      interface="true" eSuperTypes="#//IJpaContentNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jpaFile" eType="#//IJpaFile"
        changeable="false" defaultValueLiteral="" eOpposite="#//JpaFile/content"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPersistentType" abstract="true" interface="true"
      eSuperTypes="#//IJpaContentNode">
    <eOperations name="getMapping" lowerBound="1" eType="#//ITypeMapping"/>
    <eOperations name="parentPersistentType" eType="#//IPersistentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappingKey" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITypeMapping" abstract="true" interface="true"
      eSuperTypes="#//IJpaSourceObject">
    <eOperations name="getPersistentType" lowerBound="1" eType="#//IPersistentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullTypeMapping" eSuperTypes="#//JpaEObject #//ITypeMapping #//IJpaSourceObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPersistentAttribute" abstract="true"
      interface="true" eSuperTypes="#//IJpaContentNode">
    <eOperations name="typeMapping" lowerBound="1" eType="#//ITypeMapping"/>
    <eOperations name="getName" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eOperations name="mappingKey" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="defaultMappingKey" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="#//IAttributeMapping" changeable="false" volatile="true" transient="true"
        derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAttributeMapping" abstract="true" interface="true"
      eSuperTypes="#//IJpaSourceObject">
    <eOperations name="getPersistentAttribute" lowerBound="1" eType="#//IPersistentAttribute"/>
    <eOperations name="isDefault" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessType">
    <eLiterals name="Default" literal="Default"/>
    <eLiterals name="PROPERTY" value="1" literal="Property"/>
    <eLiterals name="FIELD" value="2" literal="Field"/>
  </eClassifiers>
  <eSubpackages name="mappings" nsURI="jpt.core.mappings.xmi" nsPrefix="jpt.core.mappings">
    <eClassifiers xsi:type="ecore:EClass" name="IMappedSuperclass" abstract="true"
        interface="true" eSuperTypes="#//ITypeMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="idClass" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IEntity" abstract="true" interface="true"
        eSuperTypes="#//ITypeMapping">
      <eOperations name="discriminatorValueIsAllowed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getSecondaryTables" upperBound="-1" eType="#//mappings/ISecondaryTable"/>
      <eOperations name="parentEntity" eType="#//mappings/IEntity"/>
      <eOperations name="rootEntity" eType="#//mappings/IEntity"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1"
          eType="#//mappings/ITable" changeable="false" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedSecondaryTables"
          upperBound="-1" eType="#//mappings/ISecondaryTable" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="primaryKeyJoinColumns"
          upperBound="-1" eType="#//mappings/IPrimaryKeyJoinColumn" changeable="false"
          volatile="true" transient="true" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedPrimaryKeyJoinColumns"
          upperBound="-1" eType="#//mappings/IPrimaryKeyJoinColumn" containment="true"
          resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultPrimaryKeyJoinColumns"
          upperBound="-1" eType="#//mappings/IPrimaryKeyJoinColumn" containment="true"
          resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inheritanceStrategy"
          eType="#//mappings/InheritanceType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultDiscriminatorValue"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedDiscriminatorValue"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorValue" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="discriminatorColumn"
          eType="#//mappings/IDiscriminatorColumn" changeable="false" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceGenerator" eType="#//mappings/ISequenceGenerator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tableGenerator" eType="#//mappings/ITableGenerator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeOverrides" upperBound="-1"
          eType="#//mappings/IAttributeOverride" changeable="false" volatile="true"
          transient="true" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedAttributeOverrides"
          upperBound="-1" eType="#//mappings/IAttributeOverride" containment="true"
          resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultAttributeOverrides"
          upperBound="-1" eType="#//mappings/IAttributeOverride" containment="true"
          resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationOverrides"
          upperBound="-1" eType="#//mappings/IAssociationOverride" changeable="false"
          volatile="true" transient="true" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedAssociationOverrides"
          upperBound="-1" eType="#//mappings/IAssociationOverride" containment="true"
          resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultAssociationOverrides"
          upperBound="-1" eType="#//mappings/IAssociationOverride" containment="true"
          resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namedQueries" upperBound="-1"
          eType="#//mappings/INamedQuery" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namedNativeQueries" upperBound="-1"
          eType="#//mappings/INamedNativeQuery" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="idClass" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IEmbeddable" abstract="true" interface="true"
        eSuperTypes="#//ITypeMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="ITable" abstract="true" interface="true"
        eSuperTypes="#//IJpaSourceObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="catalog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedCatalog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultCatalog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="schema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="uniqueConstraints" upperBound="-1"
          eType="#//mappings/IUniqueConstraint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IUniqueConstraint" abstract="true"
        interface="true" eSuperTypes="#//IJpaSourceObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnNames" upperBound="-1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="INamedColumn" abstract="true" interface="true"
        eSuperTypes="#//IJpaSourceObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnDefinition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IAbstractColumn" abstract="true" interface="true"
        eSuperTypes="#//mappings/INamedColumn">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="#//mappings/DefaultFalseBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="#//mappings/DefaultTrueBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="insertable" eType="#//mappings/DefaultTrueBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatable" eType="#//mappings/DefaultTrueBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="table" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IColumn" abstract="true" interface="true"
        eSuperTypes="#//mappings/IAbstractColumn">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="255"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IColumnMapping" abstract="true" interface="true">
      <eOperations name="getColumn" eType="#//mappings/IColumn"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IBasic" abstract="true" interface="true"
        eSuperTypes="#//IAttributeMapping #//mappings/IColumnMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fetch" eType="#//mappings/DefaultEagerFetchType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="#//mappings/DefaultTrueBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
          eType="#//mappings/IColumn" changeable="false" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lob" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="temporal" eType="#//mappings/TemporalType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumerated" eType="#//mappings/EnumType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IId" abstract="true" interface="true"
        eSuperTypes="#//IAttributeMapping #//mappings/IColumnMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
          eType="#//mappings/IColumn" changeable="false" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="generatedValue" eType="#//mappings/IGeneratedValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="temporal" eType="#//mappings/TemporalType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tableGenerator" eType="#//mappings/ITableGenerator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceGenerator" eType="#//mappings/ISequenceGenerator"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ITransient" abstract="true" interface="true"
        eSuperTypes="#//IAttributeMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="IVersion" abstract="true" interface="true"
        eSuperTypes="#//IAttributeMapping #//mappings/IColumnMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
          eType="#//mappings/IColumn" changeable="false" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="temporal" eType="#//mappings/TemporalType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IEmbeddedId" abstract="true" interface="true"
        eSuperTypes="#//IAttributeMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="IEmbedded" abstract="true" interface="true"
        eSuperTypes="#//IAttributeMapping">
      <eOperations name="embeddable" eType="#//mappings/IEmbeddable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeOverrides" upperBound="-1"
          eType="#//mappings/IAttributeOverride" changeable="false" volatile="true"
          transient="true" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedAttributeOverrides"
          upperBound="-1" eType="#//mappings/IAttributeOverride" containment="true"
          resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultAttributeOverrides"
          upperBound="-1" eType="#//mappings/IAttributeOverride" containment="true"
          resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IRelationshipMapping" abstract="true"
        interface="true" eSuperTypes="#//IAttributeMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetEntity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedTargetEntity"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultTargetEntity"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedTargetEntity"
          eType="#//mappings/IEntity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cascade" eType="#//mappings/ICascade"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="INonOwningMapping" abstract="true"
        interface="true" eSuperTypes="#//mappings/IRelationshipMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappedBy" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IMultiRelationshipMapping" abstract="true"
        interface="true" eSuperTypes="#//mappings/INonOwningMapping">
      <eOperations name="isNoOrdering" ordered="false" unique="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="setNoOrdering" ordered="false" unique="false"/>
      <eOperations name="isOrderByPk" ordered="false" unique="false" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
      <eOperations name="setOrderByPk" ordered="false" unique="false"/>
      <eOperations name="isCustomOrdering" ordered="false" unique="false" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderBy" ordered="false"
          unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fetch" eType="#//mappings/DefaultLazyFetchType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="joinTable" lowerBound="1"
          eType="#//mappings/IJoinTable" changeable="false" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapKey" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IOneToMany" abstract="true" interface="true"
        eSuperTypes="#//mappings/IMultiRelationshipMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="IManyToMany" abstract="true" interface="true"
        eSuperTypes="#//mappings/IMultiRelationshipMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="ISingleRelationshipMapping" abstract="true"
        interface="true" eSuperTypes="#//mappings/IRelationshipMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fetch" eType="#//mappings/DefaultEagerFetchType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="joinColumns" upperBound="-1"
          eType="#//mappings/IJoinColumn" changeable="false" volatile="true" transient="true"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedJoinColumns"
          upperBound="-1" eType="#//mappings/IJoinColumn" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultJoinColumns" upperBound="-1"
          eType="#//mappings/IJoinColumn" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="#//mappings/DefaultTrueBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IManyToOne" abstract="true" interface="true"
        eSuperTypes="#//mappings/ISingleRelationshipMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="IOneToOne" abstract="true" interface="true"
        eSuperTypes="#//mappings/ISingleRelationshipMapping #//mappings/INonOwningMapping"/>
    <eClassifiers xsi:type="ecore:EEnum" name="DefaultEagerFetchType">
      <eLiterals name="Default" literal="Default (Eager)"/>
      <eLiterals name="EAGER" value="1" literal="Eager"/>
      <eLiterals name="LAZY" value="2" literal="Lazy"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DefaultLazyFetchType">
      <eLiterals name="Default" literal="Default (Lazy)"/>
      <eLiterals name="LAZY" value="1" literal="Lazy"/>
      <eLiterals name="EAGER" value="2" literal="Eager"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DefaultFalseBoolean">
      <eLiterals name="Default" literal="Default (False)"/>
      <eLiterals name="false" value="1" literal="False"/>
      <eLiterals name="true" value="2" literal="True"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DefaultTrueBoolean">
      <eLiterals name="Default" literal="Default (False)"/>
      <eLiterals name="true" value="1" literal="True"/>
      <eLiterals name="false" value="2" literal="False"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TemporalType">
      <eLiterals name="Null" literal=""/>
      <eLiterals name="DATE" value="1" literal="Date"/>
      <eLiterals name="TIME" value="2" literal="Time"/>
      <eLiterals name="TIMESTAMP" value="3" literal="Timestamp"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IJoinTable" abstract="true" interface="true"
        eSuperTypes="#//mappings/ITable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="joinColumns" upperBound="-1"
          eType="#//mappings/IJoinColumn" changeable="false" volatile="true" transient="true"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedJoinColumns"
          upperBound="-1" eType="#//mappings/IJoinColumn" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultJoinColumns" upperBound="-1"
          eType="#//mappings/IJoinColumn" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inverseJoinColumns" upperBound="-1"
          eType="#//mappings/IJoinColumn" changeable="false" volatile="true" transient="true"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedInverseJoinColumns"
          upperBound="-1" eType="#//mappings/IJoinColumn" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultInverseJoinColumns"
          upperBound="-1" eType="#//mappings/IJoinColumn" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IAbstractJoinColumn" abstract="true"
        interface="true" eSuperTypes="#//mappings/INamedColumn">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencedColumnName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedReferencedColumnName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultReferencedColumnName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IJoinColumn" abstract="true" interface="true"
        eSuperTypes="#//mappings/IAbstractColumn #//mappings/IAbstractJoinColumn"/>
    <eClassifiers xsi:type="ecore:EClass" name="IOverride" abstract="true" interface="true"
        eSuperTypes="#//IJpaSourceObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IAttributeOverride" abstract="true"
        interface="true" eSuperTypes="#//mappings/IOverride #//mappings/IColumnMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
          eType="#//mappings/IColumn" changeable="false" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IAssociationOverride" abstract="true"
        interface="true" eSuperTypes="#//mappings/IOverride">
      <eStructuralFeatures xsi:type="ecore:EReference" name="joinColumns" upperBound="-1"
          eType="#//mappings/IJoinColumn" changeable="false" volatile="true" transient="true"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedJoinColumns"
          upperBound="-1" eType="#//mappings/IJoinColumn" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultJoinColumns" upperBound="-1"
          eType="#//mappings/IJoinColumn" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IDiscriminatorColumn" abstract="true"
        interface="true" eSuperTypes="#//mappings/INamedColumn">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminatorType" eType="#//mappings/DiscriminatorType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultLength" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          defaultValueLiteral="31"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedLength" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          defaultValueLiteral="-1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          changeable="false" volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="InheritanceType">
      <eLiterals name="Default" literal="Default (Single Table)"/>
      <eLiterals name="SINGLE_TABLE" value="1" literal="Single Table"/>
      <eLiterals name="JOINED" value="2" literal="Joined"/>
      <eLiterals name="TABLE_PER_CLASS" value="3" literal="Table per Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DiscriminatorType">
      <eLiterals name="Default" literal="Default (String)"/>
      <eLiterals name="STRING" value="1" literal="String"/>
      <eLiterals name="CHAR" value="2" literal="Char"/>
      <eLiterals name="INTEGER" value="3" literal="Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISecondaryTable" abstract="true" interface="true"
        eSuperTypes="#//mappings/ITable">
      <eOperations name="typeMapping" eType="#//ITypeMapping"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="primaryKeyJoinColumns"
          upperBound="-1" eType="#//mappings/IPrimaryKeyJoinColumn" changeable="false"
          volatile="true" transient="true" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedPrimaryKeyJoinColumns"
          upperBound="-1" eType="#//mappings/IPrimaryKeyJoinColumn" containment="true"
          resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultPrimaryKeyJoinColumns"
          upperBound="-1" eType="#//mappings/IPrimaryKeyJoinColumn" containment="true"
          resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IPrimaryKeyJoinColumn" abstract="true"
        interface="true" eSuperTypes="#//mappings/IAbstractJoinColumn"/>
    <eClassifiers xsi:type="ecore:EClass" name="IGenerator" abstract="true" interface="true"
        eSuperTypes="#//IJpaSourceObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedInitialValue"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          defaultValueLiteral="-1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultInitialValue"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="allocationSize" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedAllocationSize"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          defaultValueLiteral="-1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultAllocationSize"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
          changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ITableGenerator" abstract="true" interface="true"
        eSuperTypes="#//mappings/IGenerator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="table" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="catalog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedCatalog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultCatalog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="schema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pkColumnName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedPkColumnName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPkColumnName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueColumnName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedValueColumnName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueColumnName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pkColumnValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedPkColumnValue"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPkColumnValue"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="uniqueConstraints" upperBound="-1"
          eType="#//mappings/IUniqueConstraint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISequenceGenerator" abstract="true"
        interface="true" eSuperTypes="#//mappings/IGenerator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specifiedSequenceName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultSequenceName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IGeneratedValue" abstract="true" interface="true"
        eSuperTypes="#//IJpaSourceObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strategy" eType="#//mappings/GenerationType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="generator" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="GenerationType">
      <eLiterals name="Default" literal="Default (Auto)"/>
      <eLiterals name="AUTO" value="1" literal="Auto"/>
      <eLiterals name="IDENTITY" value="2" literal="Identity"/>
      <eLiterals name="SEQUENCE" value="3" literal="Sequence"/>
      <eLiterals name="TABLE" value="4" literal="Table"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="EnumType">
      <eLiterals name="Default" literal="Default (Ordinal)"/>
      <eLiterals name="ORDINAL" value="1" literal="Ordinal"/>
      <eLiterals name="STRING" value="2" literal="String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IQuery" abstract="true" interface="true"
        eSuperTypes="#//IJpaSourceObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hints" upperBound="-1"
          eType="#//mappings/IQueryHint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="INamedQuery" abstract="true" interface="true"
        eSuperTypes="#//IJpaSourceObject #//mappings/IQuery"/>
    <eClassifiers xsi:type="ecore:EClass" name="INamedNativeQuery" abstract="true"
        interface="true" eSuperTypes="#//IJpaSourceObject #//mappings/IQuery">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultClass" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultSetMapping" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IQueryHint" abstract="true" interface="true"
        eSuperTypes="#//IJpaSourceObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CascadeType">
      <eLiterals name="ALL" literal="All"/>
      <eLiterals name="PERSIST" value="1" literal="Persist"/>
      <eLiterals name="MERGE" value="2" literal="Merge"/>
      <eLiterals name="REMOVE" value="3" literal="Remove"/>
      <eLiterals name="REFRESH" value="4" literal="Refresh"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ICascade" abstract="true" interface="true"
        eSuperTypes="#//IJpaSourceObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="all" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="persist" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="merge" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="remove" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="refresh" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
