<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="java"
    nsURI="jpt.java.xmi" nsPrefix="org.eclipse.jpt.core.content.java">
  <eClassifiers xsi:type="ecore:EClass" name="JavaEObject" abstract="true" eSuperTypes="old_core.ecore#//JpaEObject old_core.ecore#//IJpaSourceObject">
    <eOperations name="getJpaFile" eType="ecore:EClass old_core.ecore#//IJpaFile"/>
    <eOperations name="getRoot" eType="ecore:EClass old_core.ecore#//IJpaRootContentNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JpaCompilationUnit" eSuperTypes="#//JavaEObject old_core.ecore#//IJpaRootContentNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//JavaPersistentType" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaPersistentType" eSuperTypes="#//JavaEObject old_core.ecore#//IPersistentType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" lowerBound="1"
        eType="#//IJavaTypeMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//JavaPersistentAttribute" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="ecore:EEnum old_core.ecore#//AccessType"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaPersistentAttribute" eSuperTypes="#//JavaEObject old_core.ecore#//IPersistentAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultMapping" lowerBound="1"
        eType="#//IJavaAttributeMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedMapping" lowerBound="1"
        eType="#//IJavaAttributeMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IJavaTypeMapping" abstract="true" interface="true"
      eSuperTypes="old_core.ecore#//ITypeMapping">
    <eOperations name="initialize"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IJavaAttributeMapping" abstract="true"
      interface="true" eSuperTypes="old_core.ecore#//IAttributeMapping">
    <eOperations name="initialize"/>
  </eClassifiers>
  <eSubpackages name="mappings" nsURI="jpt.core.java.mappings.xmi" nsPrefix="jpt.core.java.mappings">
    <eClassifiers xsi:type="ecore:EClass" name="JavaTypeMapping" abstract="true" eSuperTypes="#//JavaEObject #//IJavaTypeMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaEntity" eSuperTypes="#//mappings/JavaTypeMapping old_core.ecore#//mappings/IEntity"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaMappedSuperclass" eSuperTypes="#//mappings/JavaTypeMapping old_core.ecore#//mappings/IMappedSuperclass"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaEmbeddable" eSuperTypes="#//mappings/JavaTypeMapping old_core.ecore#//mappings/IEmbeddable"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaNullTypeMapping" eSuperTypes="#//mappings/JavaTypeMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaAttributeMapping" abstract="true"
        eSuperTypes="#//JavaEObject #//IJavaAttributeMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaBasic" eSuperTypes="#//mappings/JavaAttributeMapping old_core.ecore#//mappings/IBasic"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaId" eSuperTypes="#//mappings/JavaAttributeMapping old_core.ecore#//mappings/IId"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaTransient" eSuperTypes="#//mappings/JavaAttributeMapping old_core.ecore#//mappings/ITransient"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaVersion" eSuperTypes="#//mappings/JavaAttributeMapping old_core.ecore#//mappings/IVersion"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaEmbeddedId" eSuperTypes="#//mappings/JavaAttributeMapping old_core.ecore#//mappings/IEmbeddedId"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaEmbedded" eSuperTypes="#//mappings/JavaAttributeMapping old_core.ecore#//mappings/IEmbedded"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaRelationshipMapping" abstract="true"
        eSuperTypes="#//mappings/JavaAttributeMapping old_core.ecore#//mappings/IRelationshipMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaSingleRelationshipMapping" abstract="true"
        eSuperTypes="#//mappings/JavaRelationshipMapping old_core.ecore#//mappings/ISingleRelationshipMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaManyToOne" eSuperTypes="#//mappings/JavaSingleRelationshipMapping old_core.ecore#//mappings/IManyToOne"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaOneToOne" eSuperTypes="#//mappings/JavaSingleRelationshipMapping old_core.ecore#//mappings/IOneToOne"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaMultiRelationshipMapping" abstract="true"
        eSuperTypes="#//mappings/JavaRelationshipMapping old_core.ecore#//mappings/IMultiRelationshipMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaOneToMany" eSuperTypes="#//mappings/JavaMultiRelationshipMapping old_core.ecore#//mappings/IOneToMany"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaManyToMany" eSuperTypes="#//mappings/JavaMultiRelationshipMapping old_core.ecore#//mappings/IManyToMany"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaNullAttributeMapping" eSuperTypes="#//mappings/JavaAttributeMapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractJavaTable" abstract="true"
        eSuperTypes="#//JavaEObject old_core.ecore#//mappings/ITable"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaTable" eSuperTypes="#//mappings/AbstractJavaTable"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaSecondaryTable" eSuperTypes="#//mappings/AbstractJavaTable old_core.ecore#//mappings/ISecondaryTable"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaJoinTable" eSuperTypes="#//mappings/AbstractJavaTable old_core.ecore#//mappings/IJoinTable"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaNamedColumn" abstract="true" eSuperTypes="#//JavaEObject old_core.ecore#//mappings/INamedColumn"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractJavaColumn" abstract="true"
        eSuperTypes="#//mappings/JavaNamedColumn old_core.ecore#//mappings/IAbstractColumn"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaColumn" eSuperTypes="#//mappings/AbstractJavaColumn old_core.ecore#//mappings/IColumn"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaJoinColumn" eSuperTypes="#//mappings/AbstractJavaColumn old_core.ecore#//mappings/IJoinColumn"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaOverride" abstract="true" eSuperTypes="#//JavaEObject old_core.ecore#//mappings/IOverride"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaAttributeOverride" eSuperTypes="#//mappings/JavaOverride old_core.ecore#//mappings/IAttributeOverride"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaAssociationOverride" eSuperTypes="#//mappings/JavaOverride old_core.ecore#//mappings/IAssociationOverride"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaDiscriminatorColumn" eSuperTypes="#//mappings/JavaNamedColumn old_core.ecore#//mappings/IDiscriminatorColumn"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaPrimaryKeyJoinColumn" eSuperTypes="#//mappings/JavaNamedColumn old_core.ecore#//mappings/IPrimaryKeyJoinColumn"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaGeneratedValue" eSuperTypes="#//JavaEObject old_core.ecore#//mappings/IGeneratedValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaGenerator" abstract="true" eSuperTypes="#//JavaEObject old_core.ecore#//mappings/IGenerator"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaTableGenerator" eSuperTypes="#//mappings/JavaGenerator old_core.ecore#//mappings/ITableGenerator"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaSequenceGenerator" eSuperTypes="#//mappings/JavaGenerator old_core.ecore#//mappings/ISequenceGenerator"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaAbstractQuery" abstract="true"
        eSuperTypes="#//JavaEObject old_core.ecore#//mappings/IQuery"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaNamedQuery" eSuperTypes="#//mappings/JavaAbstractQuery old_core.ecore#//mappings/INamedQuery"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaNamedNativeQuery" eSuperTypes="#//mappings/JavaAbstractQuery old_core.ecore#//mappings/INamedNativeQuery"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaQueryHint" eSuperTypes="#//JavaEObject old_core.ecore#//mappings/IQueryHint"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaUniqueConstraint" eSuperTypes="#//JavaEObject old_core.ecore#//mappings/IUniqueConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaCascade" eSuperTypes="#//JavaEObject old_core.ecore#//mappings/ICascade"/>
  </eSubpackages>
</ecore:EPackage>
