<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="orm"
    nsURI="jpt2_0.orm.xmi" nsPrefix="org.eclipse.jpt.core.jpa2.resource.orm">
  <eClassifiers xsi:type="ecore:EClass" name="XmlEntityMappings" eSuperTypes="orm.ecore#//XmlEntityMappings"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlPersistenceUnitMetadata" eSuperTypes="orm.ecore#//XmlPersistenceUnitMetadata">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlPersistenceUnitDefaults" eSuperTypes="orm.ecore#//XmlPersistenceUnitDefaults">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delimitedIdentifiers" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlEntity" eSuperTypes="orm.ecore#//XmlEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheable" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlMappedSuperclass" eSuperTypes="orm.ecore#//XmlMappedSuperclass"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlEmbeddable" eSuperTypes="orm.ecore#//XmlEmbeddable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attributes" eSuperTypes="orm.ecore#//Attributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementCollections" upperBound="-1"
        eType="#//XmlElementCollection" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlAttributeMapping" abstract="true"
      interface="true" eSuperTypes="orm.ecore#//XmlAttributeMapping orm.ecore#//XmlAccessHolder"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlElementCollection" eSuperTypes="orm.ecore#//AbstractXmlAttributeMapping #//XmlAttributeMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetClass" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fetch" eType="ecore:EEnum orm.ecore#//FetchType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderBy" eType="ecore:EDataType orm.ecore#//OrderBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderColumn" eType="#//XmlOrderColumn"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKey" eType="ecore:EClass orm.ecore#//MapKey"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyClass" eType="#//XmlMapKeyClass"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapKeyTemporal" eType="ecore:EEnum orm.ecore#//TemporalType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapKeyEnumerated" eType="ecore:EEnum orm.ecore#//EnumType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyAttributeOverrides"
        upperBound="-1" eType="ecore:EClass orm.ecore#//XmlAttributeOverride" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyColumn" eType="#//XmlMapKeyColumn"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyJoinColumns" upperBound="-1"
        eType="#//XmlMapKeyJoinColumn" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" eType="ecore:EClass orm.ecore#//XmlColumn"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temporal" eType="ecore:EEnum orm.ecore#//TemporalType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumerated" eType="ecore:EEnum orm.ecore#//EnumType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lob" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeOverrides" upperBound="-1"
        eType="ecore:EClass orm.ecore#//XmlAttributeOverride" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationOverrides" upperBound="-1"
        eType="ecore:EClass orm.ecore#//XmlAssociationOverride" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionTable" eType="#//XmlCollectionTable"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlId" eSuperTypes="orm.ecore#//XmlId #//XmlAttributeMapping"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlEmbeddedId" eSuperTypes="orm.ecore#//XmlEmbeddedId #//XmlAttributeMapping"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlEmbedded" eSuperTypes="orm.ecore#//XmlEmbedded #//XmlAttributeMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationOverrides" upperBound="-1"
        eType="ecore:EClass orm.ecore#//XmlAssociationOverride" containment="true"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlBasic" eSuperTypes="orm.ecore#//XmlBasic #//XmlAttributeMapping"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlVersion" eSuperTypes="orm.ecore#//XmlVersion #//XmlAttributeMapping"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlDerivedId" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlManyToOne" eSuperTypes="orm.ecore#//XmlManyToOne #//XmlAttributeMapping #//XmlDerivedId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappedById" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlOneToMany" eSuperTypes="orm.ecore#//XmlOneToMany #//XmlAttributeMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderColumn" eType="#//XmlOrderColumn"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyClass" eType="#//XmlMapKeyClass"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapKeyTemporal" eType="ecore:EEnum orm.ecore#//TemporalType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapKeyEnumerated" eType="ecore:EEnum orm.ecore#//EnumType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyAttributeOverrides"
        upperBound="-1" eType="ecore:EClass orm.ecore#//XmlAttributeOverride" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyColumn" eType="#//XmlMapKeyColumn"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyJoinColumns" upperBound="-1"
        eType="#//XmlMapKeyJoinColumn" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orphanRemoval" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlOneToOne" eSuperTypes="orm.ecore#//XmlOneToOne #//XmlAttributeMapping #//XmlDerivedId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orphanRemoval" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappedById" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlManyToMany" eSuperTypes="orm.ecore#//XmlManyToMany #//XmlAttributeMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderColumn" eType="#//XmlOrderColumn"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyClass" eType="#//XmlMapKeyClass"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapKeyTemporal" eType="ecore:EEnum orm.ecore#//TemporalType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapKeyEnumerated" eType="ecore:EEnum orm.ecore#//EnumType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyAttributeOverrides"
        upperBound="-1" eType="ecore:EClass orm.ecore#//XmlAttributeOverride" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyColumn" eType="#//XmlMapKeyColumn"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyJoinColumns" upperBound="-1"
        eType="#//XmlMapKeyJoinColumn" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlTransient" eSuperTypes="orm.ecore#//XmlTransient #//XmlAttributeMapping"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlAssociationOverride" eSuperTypes="orm.ecore#//XmlAssociationOverride">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinTable" eType="ecore:EClass orm.ecore#//XmlJoinTable"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlAttributeOverride" eSuperTypes="orm.ecore#//XmlAttributeOverride">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityListeners" eSuperTypes="orm.ecore#//EntityListeners"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntityListener" eSuperTypes="orm.ecore#//EntityListener">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlQuery" abstract="true" interface="true"
      eSuperTypes="orm.ecore#//XmlQuery">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlNamedNativeQuery" eSuperTypes="orm.ecore#//XmlNamedNativeQuery #//XmlQuery"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlNamedQuery" eSuperTypes="orm.ecore#//XmlNamedQuery #//XmlQuery">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lockMode" eType="#//LockModeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlGenerator" abstract="true" interface="true"
      eSuperTypes="orm.ecore#//XmlGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlSequenceGenerator" eSuperTypes="orm.ecore#//XmlSequenceGenerator #//XmlGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="catalog" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schema" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlTableGenerator" eSuperTypes="orm.ecore#//XmlTableGenerator #//XmlGenerator"/>
  <eClassifiers xsi:type="ecore:EClass" name="SqlResultSetMapping" eSuperTypes="orm.ecore#//SqlResultSetMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventMethod" abstract="true" interface="true"
      eSuperTypes="orm.ecore#//EventMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostLoad" eSuperTypes="orm.ecore#//PostLoad #//EventMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="PostPersist" eSuperTypes="orm.ecore#//PostPersist #//EventMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="PostRemove" eSuperTypes="orm.ecore#//PostRemove #//EventMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="PostUpdate" eSuperTypes="orm.ecore#//PostUpdate #//EventMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrePersist" eSuperTypes="orm.ecore#//PrePersist #//EventMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="PreRemove" eSuperTypes="orm.ecore#//PreRemove #//EventMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="PreUpdate" eSuperTypes="orm.ecore#//PreUpdate #//EventMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlQueryHint" eSuperTypes="orm.ecore#//XmlQueryHint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlCollectionTable" eSuperTypes="orm.ecore#//AbstractXmlTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinColumns" upperBound="-1"
        eType="ecore:EClass orm.ecore#//XmlJoinColumn" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlOrderColumn" eSuperTypes="orm.ecore#//AbstractXmlNamedColumn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insertable" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatable" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="table" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlMapKeyColumn" eSuperTypes="orm.ecore#//XmlColumn"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlMapKeyJoinColumn" eSuperTypes="orm.ecore#//XmlJoinColumn"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlMapKeyClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlUniqueConstraint" eSuperTypes="orm.ecore#//XmlUniqueConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LockModeType">
    <eLiterals name="READ"/>
    <eLiterals name="WRITE"/>
    <eLiterals name="OPTIMISTIC"/>
    <eLiterals name="OPTIMISTIC_FORCE_INCREMENT"/>
    <eLiterals name="PESSIMISTIC_READ"/>
    <eLiterals name="PESSIMISTIC_WRITE"/>
    <eLiterals name="PESSIMISTIC_FORCE_INCREMENT"/>
  </eClassifiers>
</ecore:EPackage>
