<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="persistence"
    nsURI="jpt2_0.persistence.xmi" nsPrefix="org.eclipse.jpt2_0.core.resource.persistence">
  <eClassifiers xsi:type="ecore:EClass" name="XmlPersistence" eSuperTypes="persistence.ecore#//XmlPersistence"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlPersistenceUnit" eSuperTypes="persistence.ecore#//XmlPersistenceUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caching" unique="false"
        eType="#//XmlPersistenceUnitCachingType" defaultValueLiteral="JTA"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationMode" unique="false"
        eType="#//XmlPersistenceUnitValidationModeType" defaultValueLiteral="JTA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="XmlPersistenceUnitCachingType">
    <eLiterals name="ALL"/>
    <eLiterals name="NONE" value="1"/>
    <eLiterals name="ENABLE_SELECTIVE" value="2"/>
    <eLiterals name="DISABLE_SELECTIVE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="XmlPersistenceUnitValidationModeType">
    <eLiterals name="AUTO"/>
    <eLiterals name="CALLBACK" value="1"/>
    <eLiterals name="NONE" value="2"/>
  </eClassifiers>
</ecore:EPackage>
