<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="persistence"
    nsURI="jpt.persistence.xmi" nsPrefix="org.eclipse.jpt.core.resource.persistence">
  <eClassifiers xsi:type="ecore:EClass" name="XmlJavaClassRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaClass" ordered="false"
        unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlJarFileRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" ordered="false"
        unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlMappingFileRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" ordered="false"
        unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlPersistence" eSuperTypes="common.ecore#//JpaRootEObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistenceUnits" upperBound="-1"
        eType="#//XmlPersistenceUnit" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlPersistenceUnit" eSuperTypes="#//v2_0/XmlPersistenceUnit_2_0">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jtaDataSource" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonJtaDataSource" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingFiles" upperBound="-1"
        eType="#//XmlMappingFileRef" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jarFiles" upperBound="-1"
        eType="#//XmlJarFileRef" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//XmlJavaClassRef" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludeUnlistedClasses"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" eType="#//XmlProperties"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transactionType" unique="false"
        eType="#//XmlPersistenceUnitTransactionType" defaultValueLiteral="JTA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="XmlPersistenceUnitTransactionType">
    <eLiterals name="JTA"/>
    <eLiterals name="RESOURCE_LOCAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlProperties">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//XmlProperty" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eSubpackages name="v2_0" nsURI="jpt.persistence.v2_0.xmi" nsPrefix="org.eclipse.jpt.core.resource.persistence.v2_0">
    <eClassifiers xsi:type="ecore:EClass" name="XmlPersistenceUnit_2_0" abstract="true"
        interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sharedCacheMode" unique="false"
          eType="#//v2_0/XmlPersistenceUnitCachingType_2_0" defaultValueLiteral="UNSPECIFIED"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationMode" unique="false"
          eType="#//v2_0/XmlPersistenceUnitValidationModeType_2_0" defaultValueLiteral="AUTO"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XmlPersistenceUnitCachingType_2_0">
      <eLiterals name="ALL"/>
      <eLiterals name="NONE" value="1"/>
      <eLiterals name="ENABLE_SELECTIVE" value="2"/>
      <eLiterals name="DISABLE_SELECTIVE" value="3"/>
      <eLiterals name="UNSPECIFIED" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="XmlPersistenceUnitValidationModeType_2_0">
      <eLiterals name="AUTO"/>
      <eLiterals name="CALLBACK" value="1"/>
      <eLiterals name="NONE" value="2"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
