<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="persistence"
    nsURI="jpt.persistence.xmi" nsPrefix="org.eclipse.jpt.core.resource.persistence">
  <eClassifiers xsi:type="ecore:EClass" name="XmlPersistence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistenceUnits" upperBound="-1"
        eType="#//XmlPersistenceUnit" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" unique="false"
        lowerBound="1" eType="#//XmlVersion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlPersistenceUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jtaDataSource" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonJtaDataSource" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingFiles" upperBound="-1"
        eType="#//XmlMappingFileRef" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jarFiles" upperBound="-1"
        eType="#//XmlJarFileRef" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//XmlJavaClassRef" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludeUnlistedClasses"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" eType="#//XmlProperties"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transactionType" unique="false"
        eType="#//XmlPersistenceUnitTransactionType" defaultValueLiteral="JTA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlMappingFileRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" ordered="false"
        unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlJarFileRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" ordered="false"
        unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlJavaClassRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaClass" ordered="false"
        unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlProperties">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//XmlProperty" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="XmlPersistenceUnitTransactionType">
    <eLiterals name="JTA"/>
    <eLiterals name="RESOURCE_LOCAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="XmlVersion" instanceClassName="java.lang.String"/>
</ecore:EPackage>
