/*******************************************************************************
 * Copyright (c) 2007, 2008 Oracle. All rights reserved.
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0, which accompanies this distribution
 * and is available at http://www.eclipse.org/legal/epl-v10.html.
 * 
 * Contributors:
 *     Oracle - initial API and implementation
 ******************************************************************************/
package org.eclipse.jpt.utility.internal.model.value;

import java.util.ArrayList;
import java.util.Collection;
import java.util.IdentityHashMap;
import java.util.Iterator;

import org.eclipse.jpt.utility.internal.Transformer;
import org.eclipse.jpt.utility.internal.iterators.CompositeIterator;
import org.eclipse.jpt.utility.internal.iterators.TransformationIterator;
import org.eclipse.jpt.utility.internal.model.event.CollectionChangeEvent;
import org.eclipse.jpt.utility.internal.model.listener.CollectionChangeListener;

/**
 * A <code>CompositeCollectionValueModel</code> wraps another
 * <code>CollectionValueModel</code> and uses a <code>Transformer</code>
 * to convert each item in the wrapped collection to yet another
 * <code>CollectionValueModel</code>. This composite collection contains
 * the combined items from all these component collections.
 * 
 * NB: The wrapped collection must be an "identity set" that does not
 * contain the same item twice or this class will throw an exception.
 * 
 * Terminology:
 * - sources - the items in the wrapped collection value model; these
 * 	are converted into components by the transformer
 * - components - the component collection value models that are combined
 * 	by this composite collection value model
 */
public class CompositeCollectionValueModel<E1, E2>
	extends CollectionValueModelWrapper<E1>
	implements CollectionValueModel<E2>
{
	/**
	 * This is the (optional) user-supplied object that transforms
	 * the items in the wrapped collection to collection value models.
	 */
	private final Transformer<E1, CollectionValueModel<E2>> transformer;

	/**
	 * Cache of the component collection value models that
	 * were generated by the transformer; keyed by the item
	 * in the wrapped collection that was passed to the transformer.
	 */
	private final IdentityHashMap<E1, CollectionValueModel<E2>> components;

	/**
	 * Cache of the collections corresponding to the component
	 * collection value models above; keyed by the component
	 * collection value models.
	 * Use ArrayLists so we can use ArrayList-specific methods
	 * (e.g. #clone() and #ensureCapacity()).
	 */
	private final IdentityHashMap<CollectionValueModel<E2>, ArrayList<E2>> collections;

	/** Listener that listens to all the component collection value models. */
	private final CollectionChangeListener componentListener;

	/** Cache the size of the composite collection. */
	private int size;


	// ********** constructors **********

	/**
	 * Construct a collection value model with the specified wrapped
	 * collection value model. Use this constructor if
	 *     - the wrapped collection value model already contains other
	 *       collection value models or
	 *     - you want to override the <code>transform(E1)</code> method
	 *       instead of building a <code>Transformer</code>
	 */
	public CompositeCollectionValueModel(CollectionValueModel<? extends E1> collectionHolder) {
		this(collectionHolder, Transformer.Null.<E1, CollectionValueModel<E2>>instance());
	}

	/**
	 * Construct a collection value model with the specified wrapped
	 * collection value model and transformer.
	 */
	public CompositeCollectionValueModel(CollectionValueModel<? extends E1> collectionHolder, Transformer<E1, CollectionValueModel<E2>> transformer) {
		super(collectionHolder);
		this.transformer = transformer;
		this.components = new IdentityHashMap<E1, CollectionValueModel<E2>>();
		this.collections = new IdentityHashMap<CollectionValueModel<E2>, ArrayList<E2>>();
		this.componentListener = this.buildComponentListener();
		this.size = 0;
	}

	/**
	 * Construct a collection value model with the specified wrapped
	 * list value model. Use this constructor if
	 *     - the wrapped list value model already contains collection
	 *       value models or
	 *     - you want to override the <code>transform(E1)</code> method
	 *       instead of building a <code>Transformer</code>
	 */
	public CompositeCollectionValueModel(ListValueModel<? extends E1> listHolder) {
		this(new ListCollectionValueModelAdapter<E1>(listHolder));
	}

	/**
	 * Construct a collection value model with the specified wrapped
	 * list value model and transformer.
	 */
	public CompositeCollectionValueModel(ListValueModel<? extends E1> listHolder, Transformer<E1, CollectionValueModel<E2>> transformer) {
		this(new ListCollectionValueModelAdapter<E1>(listHolder), transformer);
	}

	/**
	 * Construct a collection value model with the specified, unchanging, wrapped
	 * collection. Use this constructor if
	 *     - the wrapped collection already contains collection
	 *       value models or
	 *     - you want to override the <code>transform(E1)</code> method
	 *       instead of building a <code>Transformer</code>
	 */
	public CompositeCollectionValueModel(Collection<? extends E1> collection) {
		this(new StaticCollectionValueModel<E1>(collection));
	}

	/**
	 * Construct a collection value model with the specified, unchanging, wrapped
	 * collection and transformer.
	 */
	public CompositeCollectionValueModel(Collection<? extends E1> collection, Transformer<E1, CollectionValueModel<E2>> transformer) {
		this(new StaticCollectionValueModel<E1>(collection), transformer);
	}


	// ********** initialization **********

	protected CollectionChangeListener buildComponentListener() {
		return new CollectionChangeListener() {
			public void itemsAdded(CollectionChangeEvent event) {
				CompositeCollectionValueModel.this.componentItemsAdded(event);
			}		
			public void itemsRemoved(CollectionChangeEvent event) {
				CompositeCollectionValueModel.this.componentItemsRemoved(event);
			}
			public void collectionCleared(CollectionChangeEvent event) {
				CompositeCollectionValueModel.this.componentCollectionCleared(event);
			}
			public void collectionChanged(CollectionChangeEvent event) {
				CompositeCollectionValueModel.this.componentCollectionChanged(event);
			}
			@Override
			public String toString() {
				return "component listener";
			}
		};
	}


	// ********** CollectionValueModel implementation **********

	public Iterator<E2> iterator() {
		return new CompositeIterator<E2>(this.buildCollectionsIterators());
	}

	protected Iterator<Iterator<E2>> buildCollectionsIterators() {
		return new TransformationIterator<ArrayList<E2>, Iterator<E2>>(this.collections.values().iterator()) {
			@Override
			protected Iterator<E2> transform(ArrayList<E2> next) {
				return next.iterator();
			}
		};
	}

	public int size() {
		return this.size;
	}


	// ********** CollectionValueModelWrapper overrides/implementation **********

	@Override
	protected void engageModel() {
		super.engageModel();
		// synch our cache *after* we start listening to the wrapped collection,
		// since its value might change when a listener is added;
		// the following will trigger the firing of a number of unnecessary events
		// (since we don't have any listeners yet),
		// but it reduces the amount of duplicate code
		this.addComponentSources(this.collectionHolder.iterator());
	}

	@Override
	protected void disengageModel() {
		super.disengageModel();
		// stop listening to the components...
		for (CollectionValueModel<E2> cvm : this.components.values()) {
			cvm.removeCollectionChangeListener(VALUES, this.componentListener);
		}
		// ...and clear the cache
		this.components.clear();
		this.collections.clear();
		this.size = 0;
	}

	/**
	 * Some component sources were added;
	 * add their corresponding items to our cache.
	 */
	@Override
	protected void itemsAdded(CollectionChangeEvent event) {
		this.addComponentSources(this.items(event));
	}

	/**
	 * Transform the specified sources to collection value models
	 * and add their items to our cache.
	 */
	protected void addComponentSources(Iterator<? extends E1> sources) {
		while (sources.hasNext()) {
			this.addComponentSource(sources.next());
		}
	}

	/**
	 * Transform the specified source to a collection value model
	 * and add its items to our cache.
	 */
	protected void addComponentSource(E1 source) {
		CollectionValueModel<E2> component = this.transform(source);
		if (this.components.put(source, component) != null) {
			throw new IllegalStateException("duplicate component: " + source);
		}
		component.addCollectionChangeListener(VALUES, this.componentListener);
		ArrayList<E2> componentCollection = new ArrayList<E2>(component.size());
		if (this.collections.put(component, componentCollection) != null) {
			throw new IllegalStateException("duplicate collection: " + source);
		}
		this.addComponentItems(component, componentCollection);
	}

	/**
	 * Some component sources were removed;
	 * remove their corresponding items from our cache.
	 */
	@Override
	protected void itemsRemoved(CollectionChangeEvent event) {
		this.removeComponentSources(this.items(event));
	}

	/**
	 * Remove the items corresponding to the specified sources
	 * from our cache.
	 */
	protected void removeComponentSources(Iterator<E1> sources) {
		while (sources.hasNext()) {
			this.removeComponentSource(sources.next());
		}
	}

	/**
	 * Remove the items corresponding to the specified source
	 * from our cache.
	 */
	protected void removeComponentSource(E1 source) {
		CollectionValueModel<E2> component = this.components.remove(source);
		if (component == null) {
			throw new IllegalStateException("missing component: " + source);
		}
		component.removeCollectionChangeListener(VALUES, this.componentListener);
		ArrayList<E2> componentCollection = this.collections.remove(component);
		if (componentCollection == null) {
			throw new IllegalStateException("missing collection: " + source);
		}
		this.clearComponentItems(componentCollection);
	}

	/**
	 * The component sources cleared;
	 * clear our cache.
	 */
	@Override
	protected void collectionCleared(CollectionChangeEvent event) {
		// copy the keys so we don't eat our own tail
		this.removeComponentSources(new ArrayList<E1>(this.components.keySet()).iterator());
	}

	/**
	 * The component sources changed;
	 * rebuild our cache.
	 */
	@Override
	protected void collectionChanged(CollectionChangeEvent event) {
		// copy the keys so we don't eat our own tail
		this.removeComponentSources(new ArrayList<E1>(this.components.keySet()).iterator());
		this.addComponentSources(this.collectionHolder.iterator());
	}


	// ********** internal methods **********

	/**
	 * Transform the specified object into a collection value model.
	 * <p>
	 * This method can be overridden by a subclass as an
	 * alternative to building a <code>Transformer</code>.
	 */
	protected CollectionValueModel<E2> transform(E1 value) {
		return this.transformer.transform(value);
	}

	/**
	 * One of the component collections had items added;
	 * synchronize our caches.
	 */
	protected void componentItemsAdded(CollectionChangeEvent event) {
		this.addComponentItems(this.componentItems(event), event.itemsSize(), this.componentCVM(event));
	}

	/**
	 * Update our cache.
	 */
	protected void addComponentItems(Iterator<E2> items, int itemsSize, CollectionValueModel<E2> cvm) {
		this.addComponentItems(items, itemsSize, this.collections.get(cvm));
	}

	/**
	 * Update our cache.
	 */
	protected void addComponentItems(CollectionValueModel<E2> itemsHolder, ArrayList<E2> componentCollection) {
		this.addComponentItems(itemsHolder.iterator(), itemsHolder.size(), componentCollection);
	}

	/**
	 * Update our size and collection cache.
	 */
	protected void addComponentItems(Iterator<E2> items, int itemsSize, ArrayList<E2> componentCollection) {
		this.size += itemsSize;
		componentCollection.ensureCapacity(componentCollection.size() + itemsSize);
		this.addItemsToCollection(items, componentCollection, VALUES);
	}

	/**
	 * One of the component collections had items removed;
	 * synchronize our caches.
	 */
	protected void componentItemsRemoved(CollectionChangeEvent event) {
		this.removeComponentItems(this.componentItems(event), event.itemsSize(), this.componentCVM(event));
	}

	/**
	 * Update our size and collection cache.
	 */
	protected void removeComponentItems(Iterator<E2> items, int itemsSize, CollectionValueModel<E2> cvm) {
		this.removeComponentItems(items, itemsSize, this.collections.get(cvm));
	}

	/**
	 * Update our size and collection cache.
	 */
	protected void clearComponentItems(ArrayList<E2> items) {
		// clone the collection so we don't eat our own tail
		@SuppressWarnings("unchecked") ArrayList<E2> clone = (ArrayList<E2>) items.clone();
		this.removeComponentItems(clone.iterator(), items.size(), items);
	}

	/**
	 * Update our size and collection cache.
	 */
	protected void removeComponentItems(Iterator<E2> items, int itemsSize, ArrayList<E2> componentCollection) {
		this.size -= itemsSize;
		this.removeItemsFromCollection(items, componentCollection, VALUES);
	}

	/**
	 * One of the component collections was cleared;
	 * synchronize our caches by clearing out the appropriate
	 * collection.
	 */
	protected void componentCollectionCleared(CollectionChangeEvent event) {
		ArrayList<E2> items = this.collections.get(this.componentCVM(event));
		this.clearComponentItems(items);
	}

	/**
	 * One of the component collections changed;
	 * synchronize our caches by clearing out the appropriate
	 * collection and then rebuilding it.
	 */
	protected void componentCollectionChanged(CollectionChangeEvent event) {
		CollectionValueModel<E2> componentCVM = this.componentCVM(event);
		ArrayList<E2> items = this.collections.get(componentCVM);
		this.clearComponentItems(items);
		this.addComponentItems(componentCVM, items);
	}

	// minimize scope of suppressed warnings
	@SuppressWarnings("unchecked")
	protected Iterator<E2> componentItems(CollectionChangeEvent event) {
		return (Iterator<E2>) event.items();
	}

	// minimize scope of suppressed warnings
	@SuppressWarnings("unchecked")
	protected CollectionValueModel<E2> componentCVM(CollectionChangeEvent event) {
		return (CollectionValueModel<E2>) event.getSource();
	}

}
