<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="orm"
    nsURI="jpt.eclipselink2_0.orm.xmi" nsPrefix="org.eclipse.jpt.eclipselink.core.v2_0.resource.orm">
  <eClassifiers xsi:type="ecore:EClass" name="XmlEntityMappings" eSuperTypes="eclipselink_orm1_1.ecore#//XmlEntityMappings"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlPersistenceUnitMetadata" eSuperTypes="eclipselink_orm.ecore#//XmlPersistenceUnitMetadata ../../org.eclipse.jpt.core/model/orm2.ecore#//XmlPersistenceUnitMetadata"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlEntity" eSuperTypes="eclipselink_orm1_1.ecore#//XmlEntity ../../org.eclipse.jpt.core/model/orm2.ecore#//XmlEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlEmbeddable" eSuperTypes="eclipselink_orm1_1.ecore#//XmlEmbeddable"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlMappedSuperclass" eSuperTypes="eclipselink_orm1_1.ecore#//XmlMappedSuperclass"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attributes" eSuperTypes="eclipselink_orm1_1.ecore#//Attributes ../../org.eclipse.jpt.core/model/orm2.ecore#//Attributes"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlEmbedded" eSuperTypes="eclipselink_orm1_1.ecore#//XmlEmbedded ../../org.eclipse.jpt.core/model/orm.ecore#//XmlAssociationOverrideContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlOneToOne" eSuperTypes="eclipselink_orm1_1.ecore#//XmlOneToOne ../../org.eclipse.jpt.core/model/orm2.ecore#//XmlOneToOne"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlOneToMany" eSuperTypes="../../org.eclipse.jpt.core/model/orm2.ecore#//XmlOneToMany eclipselink_orm1_1.ecore#//XmlOneToMany eclipselink_orm.ecore#//XmlConverterHolder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapKeyConvert" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyAssociationOverrides"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.jpt.core/model/orm2.ecore#//XmlAssociationOverride"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlManyToOne" eSuperTypes="eclipselink_orm1_1.ecore#//XmlManyToOne ../../org.eclipse.jpt.core/model/orm2.ecore#//XmlManyToOne"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlManyToMany" eSuperTypes="eclipselink_orm1_1.ecore#//XmlManyToMany ../../org.eclipse.jpt.core/model/orm2.ecore#//XmlManyToMany eclipselink_orm.ecore#//XmlConverterHolder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyAssociationOverrides"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.jpt.core/model/orm2.ecore#//XmlAssociationOverride"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapKeyConvert" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlElementCollection" eSuperTypes="../../org.eclipse.jpt.core/model/orm2.ecore#//XmlElementCollection eclipselink_orm.ecore#//XmlAttributeMapping eclipselink_orm.ecore#//XmlConvertibleMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKeyAssociationOverrides"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.jpt.core/model/orm2.ecore#//XmlAssociationOverride"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapKeyConvert" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmlOrderColumn" eSuperTypes="../../org.eclipse.jpt.core/model/orm2.ecore#//XmlOrderColumn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationMode" eType="#//OrderColumnValidationMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OrderColumnValidationMode">
    <eLiterals name="NONE"/>
    <eLiterals name="CORRECTION" value="1"/>
    <eLiterals name="EXCEPTION" value="2"/>
  </eClassifiers>
</ecore:EPackage>
